apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2021-05-08T10:09:47Z
  labels:
    io.kompose.service: alert-matcher-claim0
  name: alert-matcher-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
